apiVersion: apps/v1
kind: Deployment
metadata:
  name: codered-api
  labels:
    app: codered-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codered-api
  template:
    metadata:
      labels:
        app: codered-api
    spec:
      containers:
        - name: codered-api
          image: zen1tsu/codered-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: codered-secrets
            - configMapRef:
                name: codered-config
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: tmp
          hostPath:
            path: /tmp