apiVersion: v1
kind: Secret

metadata:
  name: codered-secrets

type: Opaque

stringData:
  DATABASE_URL: postgresql+asyncpg://neondb_owner:npg_OeF7IQu8VKMi@ep-rough-dawn-af0ucvph.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  SECRET_KEY: c8b9a1e0f1d2c3b4a5e6f7d8c9b0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8