apiVersion: v1
kind: Service
metadata:
  name: codered-api
spec:
  selector:
    app: codered-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080